export const dynamic = 'force-dynamic';

interface Section {
  passed: number;
  failed: number;
}

interface PackageStatus {
  status: 'passing' | 'failing' | 'unknown';
  last_checked: string | null;
  total: number;
  passed: number;
  failed: number;
  run_url: string | null;
  sections: Record<string, Section>;
}

type StatusData = Record<string, PackageStatus>;

async function getStatus(): Promise<StatusData> {
  try {
    // In development, you could optionally read from the local file system.
    // However, fetching from the raw GitHub URL ensures we always get the
    // latest production data, regardless of where the Next.js app is hosted.
    const res = await fetch('https://raw.githubusercontent.com/varve-ca/agency-sdks/main/docs/status.json', {
      next: { revalidate: 60 } // Revalidate every 60 seconds
    });
    
    if (!res.ok) {
      throw new Error(`Failed to fetch status: ${res.status} ${res.statusText}`);
    }
    
    return await res.json();
  } catch (error) {
    console.error('Error reading status.json:', error);
    return {};
  }
}

function timeAgo(isoDate: string | null): string {
  if (!isoDate) return 'never';
  const diff = Date.now() - new Date(isoDate).getTime();
  const mins = Math.floor(diff / 60_000);
  const hours = Math.floor(mins / 60);
  const days = Math.floor(hours / 24);
  if (days > 0) return `${days}d ago`;
  if (hours > 0) return `${hours}h ago`;
  if (mins > 0) return `${mins}m ago`;
  return 'just now';
}

function formatDate(isoDate: string | null): string {
  if (!isoDate) return 'Unknown date';
  return new Date(isoDate).toLocaleString(undefined, {
    year: 'numeric', month: 'short', day: 'numeric', 
    hour: '2-digit', minute: '2-digit', timeZoneName: 'short'
  });
}

export default async function StatusPage() {
  const data = await getStatus();

  return (
    <main className="flex flex-1 flex-col py-12 px-4 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-4xl w-full">
        <div className="mb-10 space-y-3">
          <h1 className="text-3xl font-semibold tracking-tight sm:text-4xl text-fd-foreground">API Status</h1>
          <p className="text-fd-muted-foreground text-lg max-w-2xl">
            Integration tests run weekly against live government APIs to verify our Zod schemas match the production response structures.
          </p>
        </div>

        <div className="flex flex-col gap-6">
          {Object.entries(data).map(([id, pkg]) => (
            <StatusCard key={id} id={id} pkg={pkg} />
          ))}
        </div>

        <div className="mt-12 rounded-xl border border-fd-border bg-fd-muted/30 p-6">
          <h2 className="text-base font-medium mb-2 text-fd-foreground">Validation methodology</h2>
          <p className="text-sm text-fd-muted-foreground leading-relaxed">
            Status data is generated by scheduled GitHub Actions workflows. Integration tests execute weekly against live agency endpoints, validating production responses against local Zod schemas. Schema mismatches (e.g., undocumented upstream payload changes) will immediately register as test failures on this dashboard.
          </p>
        </div>
      </div>
    </main>
  );
}

function StatusCard({ id, pkg }: { id: string; pkg: PackageStatus }) {
  const isUnknown = pkg.status === 'unknown';
  const hasSections = Object.keys(pkg.sections).length > 0;

  return (
    <div className="rounded-xl border border-fd-border bg-fd-card shadow-sm overflow-hidden">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 p-5 border-b border-fd-border bg-fd-muted/20">
        <div className="flex items-center gap-3">
          <h2 className="text-lg font-medium text-fd-foreground">@varve/{id}</h2>
          <StatusBadge status={pkg.status} />
        </div>
        
        {!isUnknown && (
          <div className="flex items-center flex-wrap gap-x-3 gap-y-1 text-sm text-fd-muted-foreground">
            <span title={formatDate(pkg.last_checked)}>
              Checked {timeAgo(pkg.last_checked)}
            </span>
            <span className="hidden sm:inline text-fd-border">•</span>
            <span>
              <span className="font-medium text-fd-foreground">{pkg.passed}</span>/{pkg.total} tests
            </span>
            {pkg.run_url && (
              <>
                <span className="hidden sm:inline text-fd-border">•</span>
                <a
                  href={pkg.run_url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="font-medium text-fd-primary hover:underline transition-colors"
                >
                  Logs
                </a>
              </>
            )}
          </div>
        )}
      </div>

      {hasSections ? (
        <div className="p-5">
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-y-3 gap-x-6">
            {Object.entries(pkg.sections).map(([name, section]) => {
              const sectionFailing = section.failed > 0;
              const sectionTotal = section.passed + section.failed;
              
              return (
                <div key={name} className="flex items-center justify-between group">
                  <div className="flex items-center gap-2.5 truncate">
                    <svg 
                      viewBox="0 0 24 24" 
                      fill="none" 
                      stroke="currentColor" 
                      strokeWidth="3" 
                      className={`w-3.5 h-3.5 flex-shrink-0 ${sectionFailing ? 'text-red-500' : 'text-green-500'}`} 
                      strokeLinecap="round" 
                      strokeLinejoin="round"
                    >
                      {sectionFailing ? (
                        <>
                          <line x1="18" y1="6" x2="6" y2="18"></line>
                          <line x1="6" y1="6" x2="18" y2="18"></line>
                        </>
                      ) : (
                        <polyline points="20 6 9 17 4 12"></polyline>
                      )}
                    </svg>
                    <span className="text-sm text-fd-foreground truncate" title={name}>{name}</span>
                  </div>
                  <span className="text-xs text-fd-muted-foreground ml-2 flex-shrink-0 opacity-0 group-hover:opacity-100 transition-opacity">
                    {section.passed}/{sectionTotal}
                  </span>
                </div>
              );
            })}
          </div>
        </div>
      ) : (
        isUnknown && (
          <div className="p-5 text-sm text-fd-muted-foreground text-center bg-fd-muted/10">
            No status data available for this package yet.
          </div>
        )
      )}
    </div>
  );
}

function StatusBadge({ status }: { status: PackageStatus['status'] }) {
  if (status === 'passing') {
    return (
      <span className="inline-flex items-center gap-1.5 rounded-md bg-green-500/10 px-2 py-1 text-xs font-medium text-green-700 dark:text-green-400 border border-green-500/20">
        <div className="w-1.5 h-1.5 rounded-full bg-green-500" />
        Operational
      </span>
    );
  }
  
  if (status === 'failing') {
    return (
      <span className="inline-flex items-center gap-1.5 rounded-md bg-red-500/10 px-2 py-1 text-xs font-medium text-red-700 dark:text-red-400 border border-red-500/20">
        <div className="w-1.5 h-1.5 rounded-full bg-red-500" />
        Failing
      </span>
    );
  }

  return (
    <span className="inline-flex items-center gap-1.5 rounded-md bg-fd-muted px-2 py-1 text-xs font-medium text-fd-muted-foreground border border-fd-border">
      <div className="w-1.5 h-1.5 rounded-full bg-fd-muted-foreground" />
      Unknown
    </span>
  );
}
